# Tribal Representation in the Global Knowledge Commons
I often refer to the combination of Wikipedia, Wikidata, and the other projects of the Wikimedia Foundation as the Global Knowledge Commons. It is the completely open online space where lots of people from many cultures and languages all around the world are coming together to build a foundation of the world's knowledge about everything. It's an incredibly messy experiment in fully democratized knowledge management that is often messy but nevertheless incredibly compelling to be a part of.

From the perspective of indigenous peoples, it represents an opportunity to set some of the record straight about how things are and how they've come to be through the long history of colonialism and the terrible results of the doctrine of discovery. The open nature of the platform also provides a way that indigenous systems of knowledge can be encoded and represented alongside other systems of knowledge, providing opportunities for increased understanding and communication between different ways that we look at and try to understand the world.

This notebook takes a dive through the basic identification of Native American Tribes in the United States as they exist today. It will touch on Alaska Native and Native Hawaiian groups to some extent, but those will require other work as well for their particular context. My main focus is to track down how the Tribes and their sovereign nation governments represent themselves in name, mainly their English language names as used in relationships with the U.S. Federal government. I'm focusing here, because many of my research objectives have to do with the land areas and other resources that the Tribes are currently stewarding. Data sources I need to connect with from BIA, U.S. Census, and other government organizations are connected with names of the Federally recognized tribes. If I hope to contribute what I can develop through these sources into the Global Knowledge Commons, I need to nail down how Tribes are currently represented and clean some things up along the way.

## Overall Objective
The most important initial thrust of my work here is to have labeled entities in Wikidata that represent the full group of Sovereign Nations that the U.S. Government recognizes, pursuant to the Federally Recognized Indian Tribe List Act of 1994 (Pub. L. 103-454, 108 Stat. 4791-4792). I have to determine whether existing entities in Wikidata that seem to match up based on labels and other identifying claims line up well enough and if there are any issues. If there are issues I find where some person or bot introduced something that's just not accurate or needs clarification, I'll consider doing so (e.g., see this [modification](https://www.wikidata.org/wiki/Q5092177)). I'll need to decide some things like whether to change labels around (e.g., Diné (Navajo) vs. Navajo (Diné)) and what all to do with claims that are without evidence or merit.

I want to make sure and record statements pointing to official web sites for the Tribes wherever I have those from sources or can track them down. This is an important first step in having the items represent the Tribes as they represent themselves online. The URLs are an important lead to more detailed, accurate, and timely information.

Messing around with what's in Wikipedia is more involved. I can already see where there are issues in how things have been done with redirects and how some of the articles are written. But Wikipedia articles are stories that I don't feel qualified to contribute to. What I'll try to do is connect the dots and point out issues I see, but it should be members from Tribes themselves who contribute there.

## Why this matters
Along with the aforementioned notes, the Global Knowledge Commons is increasingly factoring into the development of AI and all of its implications in terms of what we turn AI models onto working for us. I see this as an indigenous data sovereignty issue in that Tribes and allies working in concert with Tribes need to create the most accurate and current digital representation in the Commons. If the basis for things like the reasoning of Large Language Models is based at least partially in inaccurate, incomplete, out of date, or systemically skewed information about Indian Country, then we are going to continue perpetuating, at an accelerated pace, systemic injustice and the effects of colonialism.

In [9]:
import requests
from nested_lookup import nested_lookup
import pandas as pd
from wbmaker import WB
from fuzzywuzzy import fuzz
from fuzzywuzzy import process
import requests
from bs4 import BeautifulSoup

from wikibaseintegrator.datatypes import Item
from wikibaseintegrator.wbi_enums import ActionIfExists

In [2]:
wd = WB()

# Wikipedia List of Federally Recognized Tribes for CONUS

The [listing of Federally recognized Tribes for CONUS](https://en.wikipedia.org/wiki/List_of_federally_recognized_tribes_in_the_contiguous_United_States) is a somewhat reasonable list. It is certainly more comprehensive than what a [Wikidata query](https://w.wiki/77Ms) currently returns. The Wikidata query uses the semantics of classification as a "federally recognized Native American tribe in the United States," so it returns some of the Alaska Native villages as well. Indigenous Hawaiian peoples are often a separate classification in things like the U.S. Census, and I'll work through those as well at some point.

Ideally, we should be able to have a clear pathway into all Federally recognized Tribes as maintained in datasets from the BIA within the "Global Knowledge Commons." Right now, this is not the case, and I'm working through how to bring about alignment.

In [12]:
fed_tribes_page = "List_of_federally_recognized_tribes_in_the_contiguous_United_States"
fed_tribes_sections_api = f"https://en.wikipedia.org/w/api.php?action=parse&prop=sections&page={fed_tribes_page}&format=json"

fed_tribes_sections = requests.get(fed_tribes_sections_api).json()
tribal_list_section_index = next((i["index"] for i in fed_tribes_sections["parse"]["sections"] if i["line"] == "Alphabetical list of federally recognized tribes"), None)

tribal_list_api = f"https://en.wikipedia.org/w/api.php?action=parse&prop=links&page={fed_tribes_page}&section={tribal_list_section_index}&format=json"
tribal_list_links = requests.get(tribal_list_api).json()

tribe_pages = [i['*'] for i in tribal_list_links["parse"]["links"]]

wikipedia_tribes = pd.DataFrame(tribe_pages, columns=["tribe_page_link"])
wikipedia_tribes["site_link"] = wikipedia_tribes['tribe_page_link'].apply(lambda x: x.replace(' ', '_'))

## Redirects/Aliases

The tribal listing page shows a number of cases of names that a Tribe was "previously listed as." In digging a bit further, I found that these are not all of the names that are now redirected to a current name, and many of the listed tribe names actually redirect to something else that is not listed on that page. Redirects are built into the Mediawiki instance of EN-Wikipedia. To get at this dynamic, I wrote a couple of functions to operate against the Wikipedia API and pull back the full web of redirects in play. This gives us all the Wikipedia links that go to some page that presumably describes the tribe.

This is where we start to see some of the issues in semantic confusion represented by the Tribes not representing themselves in the global knowledge commons.

In [38]:
user_agent_header = {"User-Agent": "https://github.com/skybristol/indian_country_data"}

def get_redirects_to(page_title):
    api = f"https://en.wikipedia.org/w/api.php?action=query&titles={page_title}&redirects&format=json"
    r = requests.get(api, headers=user_agent_header).json()
    if "query" in r and "redirects" in r["query"]:
        return r["query"]["redirects"][0]["to"]
    return None

def get_redirects_from(page_title):
    if page_title is None:
        return
    api = f"https://en.wikipedia.org/w/api.php?action=query&titles={page_title}&prop=redirects&format=json"
    r = requests.get(api, headers=user_agent_header).json()
    redirects = nested_lookup('redirects', r)
    if redirects:
        return nested_lookup('title', redirects)

In [29]:
wikipedia_tribes['redirects_to'] = wikipedia_tribes.tribe_page_link.apply(get_redirects_to)

In [34]:
wikipedia_tribes["redirects_to"] = wikipedia_tribes.redirects_to.apply(lambda x: x[0] if isinstance(x, list) else None)

In [36]:
wikipedia_tribes["aliases"] = wikipedia_tribes.redirects_to.apply(get_redirects_from)

In [55]:
wikipedia_tribes['wp_tribe_name'] = wikipedia_tribes.apply(lambda x: x['redirects_to'] if x['redirects_to'] is not None else x['tribe_page_link'], axis=1)

In [58]:
wp_tribes_and_aliases = wikipedia_tribes[~wikipedia_tribes.wp_tribe_name.str.startswith("Help:")][['wp_tribe_name','aliases']].reset_index(drop=True)
wp_tribes_and_aliases.head()

,wp_tribe_name,aliases
0,Absentee Shawnee Tribe of Indians,"[Absentee-Shawnee Tribe, Absentee-Shawnee Trib..."
1,Delaware Nation,"[Delaware Nation, Oklahoma, Delaware Tribe of ..."
2,Agua Caliente Band of Cahuilla Indians,[Agua Caliente Band of Cahuilla Indians of the...
3,Ak-Chin Indian Community,None
4,Alabama–Coushatta Tribe of Texas,"[Alabama-Coushatta, Alabama-Coushatta Tribe, A..."

# Tribes in Wikidata

In [71]:
q_wd_tribes = """
SELECT ?tribe ?tribeLabel ?tribeDescription ?tribeAltLabel
WHERE {
  ?tribe p:P31 ?instance_of_statement .
  ?instance_of_statement ps:P31 wd:Q7840353 .
  ?instance_of_statement prov:wasDerivedFrom ?reference .
  ?reference pr:P248 ?stated_in .
  VALUES ?stated_in { wd:Q127419548 }
  OPTIONAL {
    ?tribe skos:altLabel ?tribeAltLabel .
    FILTER (LANG(?tribeAltLabel) = "en")
  }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
"""

wd_tribes = wd.sparql_query(q_wd_tribes)

wd_tribes_labels = wd_tribes[['tribe','tribeLabel','tribeDescription']].drop_duplicates().reset_index(drop=True)
wd_tribes_alt_labels = wd_tribes[['tribe','tribeAltLabel','tribeDescription']].dropna().drop_duplicates().reset_index(drop=True)

wd_tribe_lookup = wd_tribes.set_index('tribeLabel')['tribe'].to_dict()
wd_tribe_lookup.update(wd_tribes_alt_labels.set_index('tribeAltLabel')['tribe'].to_dict())

# BIA Tribal Leaders
Perhaps the best way to start with BIA's data is to work with their listing of Tribal Leaders. This is one of only a small number of datasets that BIA has online and public. It's a questionable source in that it's disclaimer indicates it is not really an official listing. Nevertheless, it does provide some useful details such as web sites for some Tribes, names and titles of tribal leaders, locations of Tribal Government offices, and the connections to the other DOI Bureaus on the landscape.

There are also fields for the date a tribal leader was elected and when the next election will be held. These might actually provide the best clue as to the currency of the information for some records that belie the stated currency date in something like the [data.gov representation](https://catalog.data.gov/dataset/tribal-leader-directory) for the dataset. However, looking at the record for my own Tribe, the Cherokee Nation, I see that their data is out of date and incorrect. Chuck Hoskin, Jr. was reelected for a second term on June 3, 2023. The latest date in the tribal leaders table is 2019, and it incorrectly states the "next election" for 6/22/2023. So, chances are good we can't trust this aspect of the data model as accurate or actionable.

The name of the Tribe as recognized by the U.S. Government and BIA is the most important connecting point as it will provide us the linkage to official BIA geospatial data on reservation boundaries and trust lands, which we will use in other work. We can also use the web sites listed for some Tribes as a starting point toward seeing how the Tribes reference themselves. They will each need to be visited and examined further.

In [6]:
bia_tribal_leaders = "data/TribalLeadership_Directory_-3582833694864348934.geojson"

In [7]:
import geopandas as gpd

bia_tribal_leaders_gdf = gpd.read_file(bia_tribal_leaders)

In [50]:
bia_tribal_leaders_gdf[bia_tribal_leaders_gdf['tribefullname'].str.contains('Brule')]

,OBJECTID,tribefullname,tribe,tribealternatename,tribalcomponent,salutation,firstname,middlename,lastname,suffix,...,borregion,fwsregion,lcc,npsregion,usgsregion,alaskasubsistenceregion,latitude,longtitude,tribalofficetype,geometry
287,6745,Lower Brule Sioux Tribe of the Lower Brule Res...,Lower Brule,,Tribe,,Clyde J.R.,,Estes,,...,Missouri Basin,Region 6 - Mountain-Prairie,,Midwest,Midwest,,44.079389,-99.605555,Tribal Headquarters,POINT (-11088039.688 5477736.029)

# Federal Register

In [44]:
fed_reg_tribes = requests.get("https://www.federalregister.gov/documents/full_text/html/2024/01/08/2024-00109.html")
soup_fed_reg_tribes = BeautifulSoup(fed_reg_tribes.content, 'html.parser')

first_h2_id = 'h-7'
second_h2_id = 'h-8'
third_h2_id = 'h-9'

conus_tribes = []
first_h2 = soup_fed_reg_tribes.find('h2', id=first_h2_id)
for sibling in first_h2.find_next_siblings():
    if sibling.name == 'h2' and sibling.get('id') == second_h2_id:
        break
    if sibling.name == 'p':
        conus_tribes.append(sibling.text.strip().split('(')[0].replace('\n', '').replace('  ', '').replace('Start Printed Page 946','').strip())

ak_tribes = []
second_h2 = soup_fed_reg_tribes.find('h2', id=second_h2_id)
for sibling in second_h2.find_next_siblings():
    if sibling.name == 'h2' and sibling.get('id') == third_h2_id:
        break
    if sibling.name == 'p':
        ak_tribes.append(sibling.text.strip().split('(')[0].replace('\n', '').replace('  ', '').strip())

print("CONUS Tribes:", len(conus_tribes))
print("AK Tribes:", len(ak_tribes))
print("Total Tribes:", len(conus_tribes) + len(ak_tribes))

CONUS Tribes: 347
AK Tribes: 229
Total Tribes: 576

In [56]:
for frname in conus_tribes:
    if frname not in wd_tribe_lookup:
        print(frname)

## Alaska Tribes

In [80]:
import geopandas as gpd

gdf_ak_tribes = gpd.read_file("data/AK_Federally_Recognized_Tribes.geojson")

In [83]:
gdf_ak_tribes[
    (gdf_ak_tribes['EntityName'].isin(ak_tribes))
    &
    (~gdf_ak_tribes['EntityName'].isin(wd_tribe_lookup.keys()))
].to_csv("~/Downloads/unlinked_ak_tribes.csv", index=False)

In [72]:
import requests

def search_wd(search_term):
    search_terms = list(set([search_term, search_term.split(' ')[0]]))
    for term in search_terms:
        search_api = f"https://www.wikidata.org/w/api.php?action=wbsearchentities&search={term}&language=en&format=json&limit=2"
        search_results = requests.get(search_api).json()
        if search_results["search"]:
            return [
                {
                    'term': term, 
                    'concepturi': i['concepturi'], 
                    'label': i['label'] if 'label' in i else None, 
                    'description': i['description'] if 'description' in i else None
                } for i in search_results['search']
            ]
        
    return None

for frname in ak_tribes:
    if frname not in wd_tribe_lookup:
        print(frname)
        display(search_wd(frname))
        print()

Allakaket Village

[{'term': 'Allakaket',
  'concepturi': 'http://www.wikidata.org/entity/Q79350',
  'label': 'Allakaket',
  'description': 'city in Alaska, United States'},
 {'term': 'Allakaket',
  'concepturi': 'http://www.wikidata.org/entity/Q4062541',
  'label': 'Allakaket Airport',
  'description': 'airport in Alaska, United States of America'}]

Alutiiq Tribe of Old Harbor

[{'term': 'Alutiiq',
  'concepturi': 'http://www.wikidata.org/entity/Q27992',
  'label': 'Alutiiq',
  'description': 'Eskimo–Aleut language spoken in southwestern Alaska'},
 {'term': 'Alutiiq',
  'concepturi': 'http://www.wikidata.org/entity/Q2745405',
  'label': 'Alutiiq people',
  'description': 'Alaska Native ethnic group'}]

Angoon Community Association

[{'term': 'Angoon',
  'concepturi': 'http://www.wikidata.org/entity/Q79367',
  'label': 'Angoon',
  'description': 'city'},
 {'term': 'Angoon',
  'concepturi': 'http://www.wikidata.org/entity/Q116711909',
  'label': 'Angoon',
  'description': 'power station with capacity >1MW in Skagway Hoonah Angoon Borough, Alaska'}]

Anvik Village

[{'term': 'Anvik',
  'concepturi': 'http://www.wikidata.org/entity/Q79573',
  'label': 'Anvik',
  'description': 'city in the Yukon-Koyukuk Census Area, Alaska, United States'},
 {'term': 'Anvik',
  'concepturi': 'http://www.wikidata.org/entity/Q47003610',
  'label': 'Anvik',
  'description': 'family name'}]

Artic Village

[{'term': 'Artic',
  'concepturi': 'http://www.wikidata.org/entity/Q239303',
  'label': 'Art Institute of Chicago',
  'description': 'art museum and school in Chicago, United States'},
 {'term': 'Artic',
  'concepturi': 'http://www.wikidata.org/entity/Q64732761',
  'label': 'ARTIC',
  'description': 'art database of the Art Institute of Chicago'}]

Asa'carsarmiut Tribe

None

Central Council of the Tlingit & Haida Indian Tribes

[{'term': 'Central',
  'concepturi': 'http://www.wikidata.org/entity/Q57525',
  'label': 'Central District',
  'description': 'district of Botswana'},
 {'term': 'Central',
  'concepturi': 'http://www.wikidata.org/entity/Q846323',
  'label': 'Central Region',
  'description': 'administrative region in Ghana'}]

Chalkyitsik Village

[{'term': 'Chalkyitsik',
  'concepturi': 'http://www.wikidata.org/entity/Q1059889',
  'label': 'Chalkyitsik',
  'description': 'census designated place in Yukon-Koyukuk Census Area, Alaska, United States'},
 {'term': 'Chalkyitsik',
  'concepturi': 'http://www.wikidata.org/entity/Q1837682',
  'label': 'Chalkyitsik Airport',
  'description': 'airport in Alaska, United States of America'}]

Cheesh-Na Tribe

None

Chevak Native Village

[{'term': 'Chevak',
  'concepturi': 'http://www.wikidata.org/entity/Q79343',
  'label': 'Chevak',
  'description': 'city in Kusilvak Census Area, Alaska, United States'},
 {'term': 'Chevak',
  'concepturi': 'http://www.wikidata.org/entity/Q116697519',
  'label': 'Chevak',
  'description': 'power station with capacity >1MW in Bethel Borough, Alaska'}]

Chickaloon Native Village

[{'term': 'Chickaloon',
  'concepturi': 'http://www.wikidata.org/entity/Q914161',
  'label': 'Chickaloon',
  'description': 'census-designated place in Matanuska-Susitna Borough, Alaska, United States'},
 {'term': 'Chickaloon',
  'concepturi': 'http://www.wikidata.org/entity/Q2963381',
  'label': 'Chickaloon River',
  'description': 'natural watercourse in Matanuska-Susitna Borough, Alaska, United States of America'}]

Chignik Bay Tribal Council

[{'term': 'Chignik',
  'concepturi': 'http://www.wikidata.org/entity/Q79530',
  'label': 'Chignik',
  'description': 'city in Lake and Peninsula Borough, Alaska, United States'},
 {'term': 'Chignik',
  'concepturi': 'http://www.wikidata.org/entity/Q2371148',
  'label': 'Chignik Lake',
  'description': 'census-designated place in Lake and Peninsula Borough, Alaska'}]

Chignik Lake Village

[{'term': 'Chignik',
  'concepturi': 'http://www.wikidata.org/entity/Q79530',
  'label': 'Chignik',
  'description': 'city in Lake and Peninsula Borough, Alaska, United States'},
 {'term': 'Chignik',
  'concepturi': 'http://www.wikidata.org/entity/Q2371148',
  'label': 'Chignik Lake',
  'description': 'census-designated place in Lake and Peninsula Borough, Alaska'}]

Chilkat Indian Village

[{'term': 'Chilkat',
  'concepturi': 'http://www.wikidata.org/entity/Q20199613',
  'label': 'Chilkat',
  'description': 'sculpture by Robert Murray'},
 {'term': 'Chilkat',
  'concepturi': 'http://www.wikidata.org/entity/Q12628963',
  'label': 'Chilkat',
  'description': 'native American tribe'}]

Chilkoot Indian Association

[{'term': 'Chilkoot',
  'concepturi': 'http://www.wikidata.org/entity/Q1072958',
  'label': 'Chilkoot Pass',
  'description': 'mountain pass'},
 {'term': 'Chilkoot',
  'concepturi': 'http://www.wikidata.org/entity/Q2963616',
  'label': 'Chilkoot River',
  'description': 'river in Alaska, USA'}]

Chinik Eskimo Community

[{'term': 'Chinik',
  'concepturi': 'http://www.wikidata.org/entity/Q24040442',
  'label': 'Chiniki',
  'description': 'Canadian First Nation'},
 {'term': 'Chinik',
  'concepturi': 'http://www.wikidata.org/entity/Q22493566',
  'label': 'Chiniki Creek',
  'description': 'watercourse in Alberta, Canada'}]

Chuloonawick Native Village

None

Circle Native Community

[{'term': 'Circle',
  'concepturi': 'http://www.wikidata.org/entity/Q17278',
  'label': 'circle',
  'description': 'simple curve of Euclidean geometry'},
 {'term': 'Circle',
  'concepturi': 'http://www.wikidata.org/entity/Q3677604',
  'label': 'circle of the Kingdom of Italy',
  'description': 'administrative division of the Kingdom of Italy'}]

Craig Tribal Association

[{'term': 'Craig',
  'concepturi': 'http://www.wikidata.org/entity/Q2671794',
  'label': 'Craig',
  'description': 'male given name'},
 {'term': 'Craig',
  'concepturi': 'http://www.wikidata.org/entity/Q15278582',
  'label': 'Craig',
  'description': 'family name'}]

Curyung Tribal Council

None

Douglas Indian Association

[{'term': 'Douglas',
  'concepturi': 'http://www.wikidata.org/entity/Q18569',
  'label': 'Douglas',
  'description': 'capital city of the Isle of Man'},
 {'term': 'Douglas',
  'concepturi': 'http://www.wikidata.org/entity/Q651778',
  'label': 'Douglas',
  'description': '1921-1967 aerospace manufacturer in the United States'}]

Egegik Village

[{'term': 'Egegik Village',
  'concepturi': 'http://www.wikidata.org/entity/Q69469141',
  'label': 'Egegik Village Library',
  'description': 'public library system in Alaska, USA'},
 {'term': 'Egegik Village',
  'concepturi': 'http://www.wikidata.org/entity/Q69864079',
  'label': 'Egegik Village Library',
  'description': 'public library in Egegik, Alaska, USA'}]

Eklutna Native Village

[{'term': 'Eklutna',
  'concepturi': 'http://www.wikidata.org/entity/Q3049619',
  'label': 'Eklutna',
  'description': 'native village within the Municipality of Anchorage in the U.S. state of Alaska'},
 {'term': 'Eklutna',
  'concepturi': 'http://www.wikidata.org/entity/Q3049618',
  'label': 'Eklutna River',
  'description': 'river in Alaska, United States'}]

Evansville Village

[{'term': 'Evansville',
  'concepturi': 'http://www.wikidata.org/entity/Q486459',
  'label': 'Evansville',
  'description': 'county seat of Vanderburgh County, Indiana, United States'},
 {'term': 'Evansville',
  'concepturi': 'http://www.wikidata.org/entity/Q4026988',
  'label': 'University of Evansville',
  'description': 'private university in Evansville, Indiana, United States'}]

Gulkana Village Council

[{'term': 'Gulkana',
  'concepturi': 'http://www.wikidata.org/entity/Q2282173',
  'label': 'Gulkana',
  'description': 'human settlement in Valdez–Cordova Census Area, Alaska, United States of America'},
 {'term': 'Gulkana',
  'concepturi': 'http://www.wikidata.org/entity/Q948529',
  'label': 'Gulkana River',
  'description': 'right tributary of the Copper River in Alaska'}]

Healy Lake Village

[{'term': 'Healy',
  'concepturi': 'http://www.wikidata.org/entity/Q64633',
  'label': 'George Peter Alexander Healy',
  'description': 'American painter (1813–1894)'},
 {'term': 'Healy',
  'concepturi': 'http://www.wikidata.org/entity/Q21482559',
  'label': 'Healy',
  'description': 'family name'}]

Hoonah Indian Association

[{'term': 'Hoonah',
  'concepturi': 'http://www.wikidata.org/entity/Q79525',
  'label': 'Hoonah',
  'description': 'city in Alaska, United States'},
 {'term': 'Hoonah',
  'concepturi': 'http://www.wikidata.org/entity/Q116711911',
  'label': 'Hoonah',
  'description': 'power station with capacity >1MW in Skagway Hoonah Angoon Borough, Alaska'}]

Hughes Village

[{'term': 'Hughes',
  'concepturi': 'http://www.wikidata.org/entity/Q2720749',
  'label': 'Hughes',
  'description': 'family name'},
 {'term': 'Hughes',
  'concepturi': 'http://www.wikidata.org/entity/Q196253',
  'label': 'Hughes Aircraft Company',
  'description': 'defunct American aerospace and defense contractor'}]

Huslia Village

[{'term': 'Huslia',
  'concepturi': 'http://www.wikidata.org/entity/Q80086',
  'label': 'Huslia',
  'description': 'city in Yukon-Koyukuk Census Area, Alaska, United States'},
 {'term': 'Huslia',
  'concepturi': 'http://www.wikidata.org/entity/Q32158001',
  'label': 'Huslia',
  'description': None}]

Hydaburg Cooperative Association

[{'term': 'Hydaburg',
  'concepturi': 'http://www.wikidata.org/entity/Q79680',
  'label': 'Hydaburg',
  'description': 'city in the Prince of Wales-Hyder Census Area, in the U.S. state of Alaska'},
 {'term': 'Hydaburg',
  'concepturi': 'http://www.wikidata.org/entity/Q116696263',
  'label': 'Hydaburg',
  'description': 'power station with capacity >1MW in Prince of Wales Ketchikan Borough, Alaska'}]

Igiugig Village

[{'term': 'Igiugig',
  'concepturi': 'http://www.wikidata.org/entity/Q2682014',
  'label': 'Igiugig',
  'description': 'census-designated place in Lake and Peninsula Borough, Alaska'},
 {'term': 'Igiugig',
  'concepturi': 'http://www.wikidata.org/entity/Q3084586',
  'label': 'Igiugig Airport',
  'description': 'airport in Alaska, United States of America'}]

Inupiat Community of the Arctic Slope

[{'term': 'Inupiat Community of the Arctic Slope',
  'concepturi': 'http://www.wikidata.org/entity/Q124362189',
  'label': 'Inupiat Community of the Arctic Slope',
  'description': 'federally recognized Alaska Native tribe'}]

Iqugmiut Traditional Council

None

Ivanof Bay Tribe

[{'term': 'Ivanof',
  'concepturi': 'http://www.wikidata.org/entity/Q83359135',
  'label': 'Ivanof',
  'description': 'family name'},
 {'term': 'Ivanof',
  'concepturi': 'http://www.wikidata.org/entity/Q16654835',
  'label': 'Ivanov',
  'description': 'family name (Иванов)'}]

Kaguyak Village

[{'term': 'Kaguyak Village',
  'concepturi': 'http://www.wikidata.org/entity/Q124362202',
  'label': 'Kaguyak Village',
  'description': 'Alaska Native village'},
 {'term': 'Kaguyak Village',
  'concepturi': 'http://www.wikidata.org/entity/Q19462658',
  'label': 'Kaguyak Village Site',
  'description': 'archaeological site in Alaska, United States'}]

Kaktovik Village

[{'term': 'Kaktovik Village',
  'concepturi': 'http://www.wikidata.org/entity/Q124362207',
  'label': 'Kaktovik Village',
  'description': 'federally recognized Alaska Native tribe'}]

Kasigluk Traditional Elders Council

[{'term': 'Kasigluk',
  'concepturi': 'http://www.wikidata.org/entity/Q2569800',
  'label': 'Kasigluk',
  'description': 'human settlement in Bethel Census Area, Alaska, United States of America'},
 {'term': 'Kasigluk',
  'concepturi': 'http://www.wikidata.org/entity/Q116715709',
  'label': 'Kasigluk',
  'description': 'power station with capacity >1MW in Bethel Borough, Alaska'}]

Kenaitze Indian Tribe

[{'term': 'Kenaitze',
  'concepturi': 'http://www.wikidata.org/entity/Q122418152',
  'label': 'Kenaitze',
  'description': 'native Alaskan tribe'},
 {'term': 'Kenaitze',
  'concepturi': 'http://www.wikidata.org/entity/Q27785',
  'label': "Dena'ina",
  'description': 'Indigenous language of North America'}]

King Island Native Community

[{'term': 'King Island Native Community',
  'concepturi': 'http://www.wikidata.org/entity/Q6411743',
  'label': 'King Island Native Community',
  'description': None}]

King Salmon Tribe

[{'term': 'King',
  'concepturi': 'http://www.wikidata.org/entity/Q116',
  'label': 'monarch',
  'description': 'person at the head of a monarchy'},
 {'term': 'King',
  'concepturi': 'http://www.wikidata.org/entity/Q12097',
  'label': 'king',
  'description': 'title given to the name of a male monarch'}]

Klawock Cooperative Association

[{'term': 'Klawock',
  'concepturi': 'http://www.wikidata.org/entity/Q79338',
  'label': 'Klawock',
  'description': 'city in Alaska, United States'},
 {'term': 'Klawock',
  'concepturi': 'http://www.wikidata.org/entity/Q6420011',
  'label': 'Klawock Airport',
  'description': 'airport in Alaska, United States of America'}]

Knik Tribe

[{'term': 'Knik',
  'concepturi': 'http://www.wikidata.org/entity/Q2097363',
  'label': 'Knyk',
  'description': 'village in Havlíčkův Brod District of Vysočina region'},
 {'term': 'Knik',
  'concepturi': 'http://www.wikidata.org/entity/Q49356501',
  'label': 'Knik',
  'description': 'human settlement in Matanuska-Susitna Borough, Alaska, United States of America'}]

Kokhanok Village

[{'term': 'Kokhanok',
  'concepturi': 'http://www.wikidata.org/entity/Q2137823',
  'label': 'Kokhanok',
  'description': 'census-designated place in Lake and Peninsula Borough, Alaska'},
 {'term': 'Kokhanok',
  'concepturi': 'http://www.wikidata.org/entity/Q6426598',
  'label': 'Kokhanok Airport',
  'description': 'airport in Alaska, United States of America'}]

Koyukuk Native Village

[{'term': 'Koyukuk',
  'concepturi': 'http://www.wikidata.org/entity/Q79685',
  'label': 'Koyukuk',
  'description': 'city in Yukon-Koyukuk Census Area, Alaska, United States'},
 {'term': 'Koyukuk',
  'concepturi': 'http://www.wikidata.org/entity/Q1546553',
  'label': 'Koyukuk River',
  'description': 'river in Alaska'}]

Levelock Village

[{'term': 'Levelock',
  'concepturi': 'http://www.wikidata.org/entity/Q2148252',
  'label': 'Levelock',
  'description': 'census-designated place in Lake and Peninsula Borough, Alaska'},
 {'term': 'Levelock',
  'concepturi': 'http://www.wikidata.org/entity/Q6535122',
  'label': 'Levelock Airport',
  'description': 'airport in Alaska, United States of America'}]

Lime Village

[{'term': 'Lime Village',
  'concepturi': 'http://www.wikidata.org/entity/Q2433389',
  'label': 'Lime Village',
  'description': 'human settlement in Bethel Census Area, Alaska, United States of America'},
 {'term': 'Lime Village',
  'concepturi': 'http://www.wikidata.org/entity/Q49747470',
  'label': 'Lime Village Aerodrome',
  'description': None}]

Louden Tribe

[{'term': 'Louden',
  'concepturi': 'http://www.wikidata.org/entity/Q21504883',
  'label': 'Louden',
  'description': 'family name'},
 {'term': 'Louden',
  'concepturi': 'http://www.wikidata.org/entity/Q110339777',
  'label': 'Louden',
  'description': 'given name'}]

Manley Hot Springs Village

[{'term': 'Manley',
  'concepturi': 'http://www.wikidata.org/entity/Q21488998',
  'label': 'Manley',
  'description': 'family name'},
 {'term': 'Manley',
  'concepturi': 'http://www.wikidata.org/entity/Q2172054',
  'label': 'Manley',
  'description': 'village in Cass County, Nebraska, United States'}]

McGrath Native Village

[{'term': 'McGrath',
  'concepturi': 'http://www.wikidata.org/entity/Q27365901',
  'label': 'McGrath',
  'description': 'family name'},
 {'term': 'McGrath',
  'concepturi': 'http://www.wikidata.org/entity/Q79574',
  'label': 'McGrath',
  'description': 'city in Alaska, United States'}]

Mentasta Traditional Council

[{'term': 'Mentasta',
  'concepturi': 'http://www.wikidata.org/entity/Q2731261',
  'label': 'Mentasta Lake',
  'description': 'census-designated place in Alaska, United States'},
 {'term': 'Mentasta',
  'concepturi': 'http://www.wikidata.org/entity/Q1502747',
  'label': 'Mentasta Mountains',
  'description': 'mountain range'}]

Naknek Native Village

[{'term': 'Naknek',
  'concepturi': 'http://www.wikidata.org/entity/Q751433',
  'label': 'Naknek',
  'description': 'census designated place in and the borough seat of Bristol Bay Borough, Alaska, United States'},
 {'term': 'Naknek',
  'concepturi': 'http://www.wikidata.org/entity/Q116697515',
  'label': 'Naknek',
  'description': 'power station with capacity >1MW in Bristol Bay Borough, Alaska'}]

Native Village of Akhiok

[{'term': 'Native Village of Akhiok',
  'concepturi': 'http://www.wikidata.org/entity/Q124283576',
  'label': 'Native Village of Akhiok',
  'description': 'federally recognized Alaska Native tribe'}]

Native Village of Akutan

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Aleknagik

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Ambler

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Atka

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Barrow Inupiat Traditional Government

[{'term': 'Native Village of Barrow Inupiat Traditional Government',
  'concepturi': 'http://www.wikidata.org/entity/Q6980080',
  'label': 'Native Village of Barrow Inupiat Traditional Government',
  'description': None}]

Native Village of Belkofski

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Brevig Mission

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Buckland

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Cantwell

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Chenega

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Chignik Lagoon

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Chitina

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Chuathbaluk

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Council

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Deering

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Diomede

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Eagle

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Eek

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Ekuk

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Ekwok

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Elim

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Eyak

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of False Pass

[{'term': 'Native Village of False Pass',
  'concepturi': 'http://www.wikidata.org/entity/Q124357749',
  'label': 'Native Village of False Pass',
  'description': 'federally recognized Alaska Native tribe'}]

Native Village of Fort Yukon

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Gakona

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Georgetown

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Goodnews Bay

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Hamilton

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Hooper Bay

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Kanatak

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Karluk

[{'term': 'Native Village of Karluk',
  'concepturi': 'http://www.wikidata.org/entity/Q124362201',
  'label': 'Native Village of Karluk',
  'description': 'federally recognized Alaska Native village'}]

Native Village of Kiana

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Kipnuk

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Kivalina

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Kluti Kaah

[{'term': 'Native Village of Kluti Kaah',
  'concepturi': 'http://www.wikidata.org/entity/Q16920150',
  'label': 'Native Village of Kluti Kaah',
  'description': 'Alaska Native village'}]

Native Village of Kobuk

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Kongiganak

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Koyuk

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Kwigillingok

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Kwinhagak

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Larsen Bay

[{'term': 'Native Village of Larsen Bay',
  'concepturi': 'http://www.wikidata.org/entity/Q124362226',
  'label': 'Native Village of Larsen Bay',
  'description': 'Alaska Native village'}]

Native Village of Marshall

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Mary's Igloo

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Mekoryuk

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Minto

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Nanwalek

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Napaimute

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Napakiak

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Napaskiak

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Nelson Lagoon

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Nightmute

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Nikolski

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Noatak

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Nuiqsut

[{'term': 'Native Village of Nuiqsut',
  'concepturi': 'http://www.wikidata.org/entity/Q124362170',
  'label': 'Native Village of Nuiqsut',
  'description': 'federally recognized Alaska Native tribe'}]

Native Village of Nunam Iqua

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Nunapitchuk

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Ouzinkie

[{'term': 'Native Village of Ouzinkie',
  'concepturi': 'http://www.wikidata.org/entity/Q124362174',
  'label': 'Native Village of Ouzinkie',
  'description': 'Alaska Native village'}]

Native Village of Paimiut

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Perryville

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Pilot Point

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Point Hope

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Point Lay

[{'term': 'Native Village of Point Lay',
  'concepturi': 'http://www.wikidata.org/entity/Q124362175',
  'label': 'Native Village of Point Lay',
  'description': 'federally recognized Alaska Native tribe'}]

Native Village of Port Graham

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Port Heiden

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Port Lions

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Ruby

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Saint Michael

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Savoonga

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Scammon Bay

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Selawik

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Shaktoolik

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Shishmaref

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Shungnak

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Stevens

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Tanacross

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Tanana

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Tatitlek

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Tazlina

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Teller

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Tetlin

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Tuntutuliak

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Tununak

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Tyonek

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Unalakleet

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of Unga

[{'term': 'Native Village of Unga',
  'concepturi': 'http://www.wikidata.org/entity/Q124357765',
  'label': 'Native Village of Unga',
  'description': 'federally recognized Alaska Native tribe'}]

Native Village of Wales

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Native Village of White Mountain

[{'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q1940766',
  'label': 'Native',
  'description': '2013 album by OneRepublic'},
 {'term': 'Native',
  'concepturi': 'http://www.wikidata.org/entity/Q2187908',
  'label': 'native',
  'description': 'software or data-formats designed to run on a particular operating system or processor'}]

Nenana Native Association

[{'term': 'Nenana',
  'concepturi': 'http://www.wikidata.org/entity/Q80058',
  'label': 'Nenana',
  'description': 'city in Alaska, USA'},
 {'term': 'Nenana',
  'concepturi': 'http://www.wikidata.org/entity/Q6991533',
  'label': 'Nenana',
  'description': None}]

New Koliganek Village Council

[{'term': 'New',
  'concepturi': 'http://www.wikidata.org/entity/Q33979',
  'label': 'Newar',
  'description': 'Sino-Tibetan language of central-eastern Nepal'},
 {'term': 'New',
  'concepturi': 'http://www.wikidata.org/entity/Q15730367',
  'label': 'Next Entertainment World',
  'description': 'South Korean film distribution company'}]

Newhalen Village

[{'term': 'Newhalen',
  'concepturi': 'http://www.wikidata.org/entity/Q79547',
  'label': 'Newhalen',
  'description': 'city in Alaska'},
 {'term': 'Newhalen',
  'concepturi': 'http://www.wikidata.org/entity/Q116711813',
  'label': 'Newhalen',
  'description': 'power station with capacity >1MW in Lake and Peninsula Borough, Alaska'}]

Newtok Village

[{'term': 'Newtok',
  'concepturi': 'http://www.wikidata.org/entity/Q1925873',
  'label': 'Newtok',
  'description': 'census-designated place in the Bethel Census Area in Alaska, United States'},
 {'term': 'Newtok',
  'concepturi': 'http://www.wikidata.org/entity/Q4328379',
  'label': 'Newtok Airport',
  'description': 'airport in Bethel Census Area, United States of America'}]

Nikolai Village

[{'term': 'Nikolai',
  'concepturi': 'http://www.wikidata.org/entity/Q659905',
  'label': 'Mikołów',
  'description': 'town in Silesia, in southern Poland'},
 {'term': 'Nikolai',
  'concepturi': 'http://www.wikidata.org/entity/Q5486169',
  'label': 'Nikolai',
  'description': 'male given name (Николай)'}]

Ninilchik Village

[{'term': 'Ninilchik',
  'concepturi': 'http://www.wikidata.org/entity/Q1493148',
  'label': 'Ninilchik',
  'description': 'census designated place in Kenai Peninsula Borough, Alaska, United States'},
 {'term': 'Ninilchik',
  'concepturi': 'http://www.wikidata.org/entity/Q3342003',
  'label': 'Ninilchik River',
  'description': 'river in the United States of America'}]

Nome Eskimo Community

[{'term': 'Nome',
  'concepturi': 'http://www.wikidata.org/entity/Q202595',
  'label': 'prefecture of Greece',
  'description': 'former administrative division of Greece'},
 {'term': 'Nome',
  'concepturi': 'http://www.wikidata.org/entity/Q79996',
  'label': 'Nome',
  'description': 'city in Alaska, USA'}]

Nondalton Village

[{'term': 'Nondalton',
  'concepturi': 'http://www.wikidata.org/entity/Q79326',
  'label': 'Nondalton',
  'description': 'city in the Lake and Peninsula Borough, Alaska, United States'},
 {'term': 'Nondalton',
  'concepturi': 'http://www.wikidata.org/entity/Q7049256',
  'label': 'Nondalton Airport',
  'description': 'airport in Alaska, United States of America'}]

Noorvik Native Community

[{'term': 'Noorvik',
  'concepturi': 'http://www.wikidata.org/entity/Q79377',
  'label': 'Noorvik',
  'description': 'city in the Northwest Arctic Borough, Alaska, United States'},
 {'term': 'Noorvik',
  'concepturi': 'http://www.wikidata.org/entity/Q116697522',
  'label': 'Noorvik',
  'description': 'power station with capacity >1MW in Northwest Arctic Borough, Alaska'}]

Nulato Village

[{'term': 'Nulato',
  'concepturi': 'http://www.wikidata.org/entity/Q79392',
  'label': 'Nulato',
  'description': 'city in Alaska'},
 {'term': 'Nulato',
  'concepturi': 'http://www.wikidata.org/entity/Q3015963',
  'label': 'Nulato Airport',
  'description': 'airport in Alaska, United States of America'}]

Nunakauyarmiut Tribe

None

Organized Village of Grayling

[{'term': 'Organized',
  'concepturi': 'http://www.wikidata.org/entity/Q87717297',
  'label': 'Organized',
  'description': '2014 documentary film by Jürgen Brügger und Jörg Haaßengier'},
 {'term': 'Organized',
  'concepturi': 'http://www.wikidata.org/entity/Q3282563',
  'label': 'Organized',
  'description': 'album by Morgan Nicholls'}]

Organized Village of Kake

[{'term': 'Organized',
  'concepturi': 'http://www.wikidata.org/entity/Q87717297',
  'label': 'Organized',
  'description': '2014 documentary film by Jürgen Brügger und Jörg Haaßengier'},
 {'term': 'Organized',
  'concepturi': 'http://www.wikidata.org/entity/Q3282563',
  'label': 'Organized',
  'description': 'album by Morgan Nicholls'}]

Organized Village of Kasaan

[{'term': 'Organized',
  'concepturi': 'http://www.wikidata.org/entity/Q87717297',
  'label': 'Organized',
  'description': '2014 documentary film by Jürgen Brügger und Jörg Haaßengier'},
 {'term': 'Organized',
  'concepturi': 'http://www.wikidata.org/entity/Q3282563',
  'label': 'Organized',
  'description': 'album by Morgan Nicholls'}]

Organized Village of Kwethluk

[{'term': 'Organized',
  'concepturi': 'http://www.wikidata.org/entity/Q87717297',
  'label': 'Organized',
  'description': '2014 documentary film by Jürgen Brügger und Jörg Haaßengier'},
 {'term': 'Organized',
  'concepturi': 'http://www.wikidata.org/entity/Q3282563',
  'label': 'Organized',
  'description': 'album by Morgan Nicholls'}]

Organized Village of Saxman

[{'term': 'Organized',
  'concepturi': 'http://www.wikidata.org/entity/Q87717297',
  'label': 'Organized',
  'description': '2014 documentary film by Jürgen Brügger und Jörg Haaßengier'},
 {'term': 'Organized',
  'concepturi': 'http://www.wikidata.org/entity/Q3282563',
  'label': 'Organized',
  'description': 'album by Morgan Nicholls'}]

Oscarville Traditional Village

[{'term': 'Oscarville',
  'concepturi': 'http://www.wikidata.org/entity/Q2314665',
  'label': 'Oscarville',
  'description': 'human settlement in Bethel Census Area, Alaska, United States of America'},
 {'term': 'Oscarville',
  'concepturi': 'http://www.wikidata.org/entity/Q124619726',
  'label': 'Oscarville, Georgia',
  'description': 'ghost town in the U.S. state of Georgia'}]

Pauloff Harbor Village

[{'term': 'Pauloff',
  'concepturi': 'http://www.wikidata.org/entity/Q47413913',
  'label': 'Pauloff',
  'description': 'family name'},
 {'term': 'Pauloff',
  'concepturi': 'http://www.wikidata.org/entity/Q2061347',
  'label': 'Pauloff Harbor',
  'description': 'airport in Alaska, United States of America'}]

Pedro Bay Village

[{'term': 'Pedro',
  'concepturi': 'http://www.wikidata.org/entity/Q15897419',
  'label': 'Pedro',
  'description': 'male given name'},
 {'term': 'Pedro',
  'concepturi': 'http://www.wikidata.org/entity/Q179773',
  'label': 'Pedro',
  'description': 'Spanish association football player'}]

Petersburg Indian Association

[{'term': 'Petersburg',
  'concepturi': 'http://www.wikidata.org/entity/Q656',
  'label': 'Saint Petersburg',
  'description': 'federal city in and former capital of Russia'},
 {'term': 'Petersburg',
  'concepturi': 'http://www.wikidata.org/entity/Q511964',
  'label': 'Petersburg',
  'description': 'independent city in Virginia, United States'}]

Pilot Station Traditional Village

[{'term': 'Pilot',
  'concepturi': 'http://www.wikidata.org/entity/Q2095549',
  'label': 'aircraft pilot',
  'description': 'person controlling an aircraft in flight'},
 {'term': 'Pilot',
  'concepturi': 'http://www.wikidata.org/entity/Q653916',
  'label': 'television pilot',
  'description': 'trial episode made to sell a television series'}]

Pitka's Point Traditional Council

[{'term': "Pitka's",
  'concepturi': 'http://www.wikidata.org/entity/Q24318246',
  'label': 'Pitkä Surnujärvi',
  'description': 'lake in Inari, Finland'},
 {'term': "Pitka's",
  'concepturi': 'http://www.wikidata.org/entity/Q108639120',
  'label': 'Pitkä Särkijärvi',
  'description': 'lake or pond in Rautalampi, Finland'}]

Platinum Traditional Village

[{'term': 'Platinum',
  'concepturi': 'http://www.wikidata.org/entity/Q880',
  'label': 'platinum',
  'description': 'chemical element with symbol Pt and atomic number 78'},
 {'term': 'Platinum',
  'concepturi': 'http://www.wikidata.org/entity/Q1576758',
  'label': 'Platinum Games',
  'description': 'Japanese computer- and video game development company'}]

Portage Creek Village

[{'term': 'Portage',
  'concepturi': 'http://www.wikidata.org/entity/Q908542',
  'label': 'Portage',
  'description': 'Linux package management system'},
 {'term': 'Portage',
  'concepturi': 'http://www.wikidata.org/entity/Q1522907',
  'label': 'portage trail',
  'description': 'trail or site used for carrying water craft or cargo over land'}]

Pribilof Islands Aleut Communities of St. Paul & St. George Islands

[{'term': 'Pribilof',
  'concepturi': 'http://www.wikidata.org/entity/Q1144173',
  'label': 'Pribilof Islands',
  'description': 'group of islands in Aleutians West Census Area, Alaska, United States'},
 {'term': 'Pribilof',
  'concepturi': 'http://www.wikidata.org/entity/Q1501292',
  'label': 'Pribilof Island shrew',
  'description': 'species of mammal'}]

Qagan Tayagungin Tribe of Sand Point

[{'term': 'Qagan',
  'concepturi': 'http://www.wikidata.org/entity/Q187878',
  'label': 'khagan',
  'description': 'imperial title of Turco-Mongol societies'},
 {'term': 'Qagan',
  'concepturi': 'http://www.wikidata.org/entity/Q49279269',
  'label': 'Qagan Us',
  'description': None}]

Rampart Village

[{'term': 'Rampart',
  'concepturi': 'http://www.wikidata.org/entity/Q1416685',
  'label': 'rampart',
  'description': 'length of bank or wall forming part of the defensive boundary of a fortification'},
 {'term': 'Rampart',
  'concepturi': 'http://www.wikidata.org/entity/Q2046960',
  'label': 'Rampart',
  'description': 'human settlement in Yukon–Koyukuk Census Area, Alaska, United States of America'}]

Saint George Island

[{'term': 'Saint',
  'concepturi': 'http://www.wikidata.org/entity/Q43115',
  'label': 'saint',
  'description': 'person who has been recognized for having an exceptional degree of holiness, sanctity, and virtue. A saint also may or may not be a canonised saint.'},
 {'term': 'Saint',
  'concepturi': 'http://www.wikidata.org/entity/Q3464126',
  'label': 'Catholic saint',
  'description': 'person deemed by the Catholic Church to be in Heaven, and worthy of public veneration'}]

Saint Paul Island

[{'term': 'Saint Paul Island',
  'concepturi': 'http://www.wikidata.org/entity/Q954281',
  'label': 'Saint Paul Island',
  'description': 'island in Alaska, United States'},
 {'term': 'Saint Paul Island',
  'concepturi': 'http://www.wikidata.org/entity/Q49676953',
  'label': 'Saint Paul Island',
  'description': 'island in St. Louis County, Minnesota, United States of America'}]

Seldovia Village Tribe

[{'term': 'Seldovia',
  'concepturi': 'http://www.wikidata.org/entity/Q79430',
  'label': 'Seldovia',
  'description': 'city in Alaska, United States'},
 {'term': 'Seldovia',
  'concepturi': 'http://www.wikidata.org/entity/Q83649696',
  'label': 'Seldovia',
  'description': 'ship built in 1945'}]

Shageluk Native Village

[{'term': 'Shageluk',
  'concepturi': 'http://www.wikidata.org/entity/Q80081',
  'label': 'Shageluk',
  'description': 'city in Yukon-Koyukuk Census Area, Alaska, United States'},
 {'term': 'Shageluk',
  'concepturi': 'http://www.wikidata.org/entity/Q4519296',
  'label': 'Shageluk Airport',
  'description': 'airport in Alaska, United States of America'}]

Sitka Tribe of Alaska

[{'term': 'Sitka',
  'concepturi': 'http://www.wikidata.org/entity/Q79804',
  'label': 'Sitka',
  'description': 'city-borough in Alaska, USA'},
 {'term': 'Sitka',
  'concepturi': 'http://www.wikidata.org/entity/Q27940849',
  'label': 'Sitka',
  'description': "character from Disney's Brother Bear"}]

Skagway Village

[{'term': 'Skagway',
  'concepturi': 'http://www.wikidata.org/entity/Q615975',
  'label': 'Skagway',
  'description': 'city in Alaska, United States'},
 {'term': 'Skagway',
  'concepturi': 'http://www.wikidata.org/entity/Q16302941',
  'label': 'Skagway',
  'description': 'human settlement in United States of America'}]

Stebbins Community Association

[{'term': 'Stebbins',
  'concepturi': 'http://www.wikidata.org/entity/Q79689',
  'label': 'Stebbins',
  'description': 'city in Nome Census Area, Alaska, United States'},
 {'term': 'Stebbins',
  'concepturi': 'http://www.wikidata.org/entity/Q540929',
  'label': '2300 Stebbins',
  'description': 'asteroid'}]

Sun'aq Tribe of Kodiak

[{'term': "Sun'aq",
  'concepturi': 'http://www.wikidata.org/entity/Q79985',
  'label': 'Kodiak',
  'description': 'city in Alaska, USA'},
 {'term': "Sun'aq",
  'concepturi': 'http://www.wikidata.org/entity/Q45535891',
  'label': 'Sun Aquan',
  'description': 'person, CBDB = 168357'}]

Takotna Village

[{'term': 'Takotna',
  'concepturi': 'http://www.wikidata.org/entity/Q2297507',
  'label': 'Takotna',
  'description': 'human settlement in Yukon–Koyukuk Census Area, Alaska, United States of America'},
 {'term': 'Takotna',
  'concepturi': 'http://www.wikidata.org/entity/Q1436431',
  'label': 'Takotna River',
  'description': 'river in Alaska'}]

Tangirnaq Native Village

None

Telida Village

[{'term': 'Telida',
  'concepturi': 'http://www.wikidata.org/entity/Q1837426',
  'label': 'Telida',
  'description': 'unincorporated community in Alaska'},
 {'term': 'Telida',
  'concepturi': 'http://www.wikidata.org/entity/Q17183383',
  'label': 'Telida Airport',
  'description': 'airport in Yukon–Koyukuk Census Area, United States of America'}]

Traditional Village of Togiak

[{'term': 'Traditional',
  'concepturi': 'http://www.wikidata.org/entity/Q56260622',
  'label': 'traditional',
  'description': 'special purpose artist used for composing and songwriting credits. Used instead of  anonymous (Q4233718) or unknown (Q56678558) when the work is better described as having emerged from a musical tradition'},
 {'term': 'Traditional',
  'concepturi': 'http://www.wikidata.org/entity/Q8201',
  'label': 'sinograms',
  'description': 'logographic writing system with Han origin used in the Sinosphere for Chinese, Japanese, Korean and traditional Vietnamese languages'}]

Tuluksak Native Community

[{'term': 'Tuluksak',
  'concepturi': 'http://www.wikidata.org/entity/Q2255196',
  'label': 'Tuluksak',
  'description': 'human settlement in Bethel Census Area, Alaska, United States of America'},
 {'term': 'Tuluksak',
  'concepturi': 'http://www.wikidata.org/entity/Q3541989',
  'label': 'Tuluksak',
  'description': 'stream in Bethel Census Area, United States of America'}]

Twin Hills Village

[{'term': 'Twin',
  'concepturi': 'http://www.wikidata.org/entity/Q159979',
  'label': 'twin',
  'description': 'one of two offspring produced in the same pregnancy'},
 {'term': 'Twin',
  'concepturi': 'http://www.wikidata.org/entity/Q14756018',
  'label': 'twins',
  'description': 'two offspring produced in the same pregnancy (use with P31 on items for both twins - if known, item for "identical twins" or "fraternal twins" is preferred)'}]

Ugashik Village

[{'term': 'Ugashik',
  'concepturi': 'http://www.wikidata.org/entity/Q1837575',
  'label': 'Ugashik',
  'description': 'census-designated place in Lake and Peninsula Borough, Alaska'},
 {'term': 'Ugashik',
  'concepturi': 'http://www.wikidata.org/entity/Q788438',
  'label': 'Ugashik River',
  'description': 'stream in Alaska'}]

Umkumiut Native Village

[{'term': 'Umkumiut',
  'concepturi': 'http://www.wikidata.org/entity/Q7881602',
  'label': 'Umkumiut',
  'description': 'hunting and fishing camp'},
 {'term': 'Umkumiut',
  'concepturi': 'http://www.wikidata.org/entity/Q3548233',
  'label': 'Umkumiute',
  'description': 'human settlement in United States of America'}]

Village of Anaktuvuk Pass

[{'term': 'Village of Anaktuvuk Pass',
  'concepturi': 'http://www.wikidata.org/entity/Q124283575',
  'label': 'Village of Anaktuvuk Pass',
  'description': 'federally recognized Alaska Native village'}]

Village of Atmautluak

[{'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q532',
  'label': 'village',
  'description': 'small clustered human settlement smaller than a town'},
 {'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q13100073',
  'label': 'village',
  'description': 'type of grassroots mass autonomous organization in China'}]

Village of Bill Moore's Slough

[{'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q532',
  'label': 'village',
  'description': 'small clustered human settlement smaller than a town'},
 {'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q13100073',
  'label': 'village',
  'description': 'type of grassroots mass autonomous organization in China'}]

Village of Chefornak

[{'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q532',
  'label': 'village',
  'description': 'small clustered human settlement smaller than a town'},
 {'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q13100073',
  'label': 'village',
  'description': 'type of grassroots mass autonomous organization in China'}]

Village of Clarks Point

[{'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q532',
  'label': 'village',
  'description': 'small clustered human settlement smaller than a town'},
 {'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q13100073',
  'label': 'village',
  'description': 'type of grassroots mass autonomous organization in China'}]

Village of Crooked Creek

[{'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q532',
  'label': 'village',
  'description': 'small clustered human settlement smaller than a town'},
 {'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q13100073',
  'label': 'village',
  'description': 'type of grassroots mass autonomous organization in China'}]

Village of Dot Lake

[{'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q532',
  'label': 'village',
  'description': 'small clustered human settlement smaller than a town'},
 {'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q13100073',
  'label': 'village',
  'description': 'type of grassroots mass autonomous organization in China'}]

Village of Iliamna

[{'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q532',
  'label': 'village',
  'description': 'small clustered human settlement smaller than a town'},
 {'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q13100073',
  'label': 'village',
  'description': 'type of grassroots mass autonomous organization in China'}]

Village of Kalskag

[{'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q532',
  'label': 'village',
  'description': 'small clustered human settlement smaller than a town'},
 {'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q13100073',
  'label': 'village',
  'description': 'type of grassroots mass autonomous organization in China'}]

Village of Kaltag

[{'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q532',
  'label': 'village',
  'description': 'small clustered human settlement smaller than a town'},
 {'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q13100073',
  'label': 'village',
  'description': 'type of grassroots mass autonomous organization in China'}]

Village of Kotlik

[{'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q532',
  'label': 'village',
  'description': 'small clustered human settlement smaller than a town'},
 {'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q13100073',
  'label': 'village',
  'description': 'type of grassroots mass autonomous organization in China'}]

Village of Lower Kalskag

[{'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q532',
  'label': 'village',
  'description': 'small clustered human settlement smaller than a town'},
 {'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q13100073',
  'label': 'village',
  'description': 'type of grassroots mass autonomous organization in China'}]

Village of Ohogamiut

[{'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q532',
  'label': 'village',
  'description': 'small clustered human settlement smaller than a town'},
 {'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q13100073',
  'label': 'village',
  'description': 'type of grassroots mass autonomous organization in China'}]

Village of Red Devil

[{'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q532',
  'label': 'village',
  'description': 'small clustered human settlement smaller than a town'},
 {'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q13100073',
  'label': 'village',
  'description': 'type of grassroots mass autonomous organization in China'}]

Village of Sleetmute

[{'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q532',
  'label': 'village',
  'description': 'small clustered human settlement smaller than a town'},
 {'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q13100073',
  'label': 'village',
  'description': 'type of grassroots mass autonomous organization in China'}]

Village of Solomon

[{'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q532',
  'label': 'village',
  'description': 'small clustered human settlement smaller than a town'},
 {'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q13100073',
  'label': 'village',
  'description': 'type of grassroots mass autonomous organization in China'}]

Village of Stony River

[{'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q532',
  'label': 'village',
  'description': 'small clustered human settlement smaller than a town'},
 {'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q13100073',
  'label': 'village',
  'description': 'type of grassroots mass autonomous organization in China'}]

Village of Venetie

[{'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q532',
  'label': 'village',
  'description': 'small clustered human settlement smaller than a town'},
 {'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q13100073',
  'label': 'village',
  'description': 'type of grassroots mass autonomous organization in China'}]

Village of Wainwright

[{'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q532',
  'label': 'village',
  'description': 'small clustered human settlement smaller than a town'},
 {'term': 'Village',
  'concepturi': 'http://www.wikidata.org/entity/Q13100073',
  'label': 'village',
  'description': 'type of grassroots mass autonomous organization in China'}]

Wrangell Cooperative Association

[{'term': 'Wrangell',
  'concepturi': 'http://www.wikidata.org/entity/Q43983',
  'label': 'Wrangell',
  'description': 'city and borough in Alaska, United States'},
 {'term': 'Wrangell',
  'concepturi': 'http://www.wikidata.org/entity/Q689100',
  'label': 'Wrangel family',
  'description': 'noble family'}]

Yakutat Tlingit Tribe

[{'term': 'Yakutat Tlingit Tribe',
  'concepturi': 'http://www.wikidata.org/entity/Q126361957',
  'label': 'Yakutat Tlingit Tribe',
  'description': None}]

Yupiit of Andreafski

[{'term': 'Yupiit',
  'concepturi': 'http://www.wikidata.org/entity/Q8061422',
  'label': 'Yupiit School District',
  'description': 'school district of Alaska, United States'},
 {'term': 'Yupiit',
  'concepturi': 'http://www.wikidata.org/entity/Q18749557',
  'label': 'Yupiit Piciryarait Cultural Center',
  'description': 'non-profit cultural center in the United States'}]

# List Comparison

# Identifiers
By and large, we are dealing with names as identifiers for Tribes. In the BIA Tribal Leaders dataset, we have three fields represending names (TribeFullName, TribeAlternateName, and Tribe). In Wikipedia, we have the names of the tribes from the listing pointing to Wikipedia pages, many of which have redirects which provide alternate names. If we connect the dots to Wikidata, we have additional possibilities for names and alternate names, some of which provide a rich source of the names Tribes call themselves in some circumstances (e.g., Diné vs. Navajo).

Interestingly, we have at least one example in the Wikidata item for the [Cherokee Nation](https://www.wikidata.org/wiki/Q14708404) where there are a number of additional identifiers for the entity, including one from the [Research Organization Registry](https://ror.org/00p23dy23), itself another interesting source for identifier connection. The Cherokee Nation Wikidata item is particularly well developed compared to many others. This may be do to the broad reach of [Cherokee Nation Businesses](https://www.wikidata.org/wiki/Q5092178) and their role in government contracting, including government R&D work across a number of agencies.

Once I nail down what existing Wikidata entities align with Wikipedia pages and BIA Tribes, I can critically examine what all statements have been made, including statements for external identifiers. I can already see some cases where external ID claims made are not really accurate until they are qualified in some way as to their significance. For instance, the ISNI reference for the item representing the [Diné](https://www.wikidata.org/wiki/Q5092178) points to something that is for a "[musical group or band](https://isni.org/isni/0000000472000739)." In whatever circumstance (I haven't tracked that down), that claim made sense at some level for whoever meant it. But if the person or bot making the claim didn't record the reasoning through reference and qualifiers, we can't know what that context was.

In [64]:
tribal_leaders[
    (tribal_leaders['TribeFullName'].isin(wp_tribes_and_aliases['wp_tribe_name']))
    |
    (tribal_leaders['TribeAlternateName'].isin(wp_tribes_and_aliases['wp_tribe_name']))
    |
    (tribal_leaders['Tribe'].isin(wp_tribes_and_aliases['wp_tribe_name']))
    |
    (tribal_leaders['TribeFullName'].isin(wp_tribes_and_aliases[['aliases']].explode('aliases')['aliases']))
    |
    (tribal_leaders['TribeAlternateName'].isin(wp_tribes_and_aliases[['aliases']].explode('aliases')['aliases']))
    |
    (tribal_leaders['Tribe'].isin(wp_tribes_and_aliases[['aliases']].explode('aliases')['aliases']))
]

,TribeFullName,Tribe,TribeAlternateName,TribalComponent,Salutation,FirstName,MiddleName,LastName,Suffix,Aka,...,ANCSARegion,BLMRegion,BORRegion,FWSRegion,LCC,NPSRegion,USGSRegion,AlaskaSubsistenceRegion,Latitude,Longtitude
0,"Confederated Tribes of the Coos, Lower Umpqua ...",Confederated Coos,NaN,Tribe,NaN,Brad,NaN,Kneaper,NaN,NaN,...,NaN,Oregon/Washington,Columbia-Pacific Northwest,Region 1 - Pacific,NaN,Pacific West,Northwest,NaN,43.383287,-124.264684
1,Confederated Tribes and Bands of the Yakama Na...,Confederated Yakama,NaN,Tribe,NaN,Gerald,NaN,Lewis,NaN,NaN,...,NaN,Oregon/Washington,Columbia-Pacific Northwest,Region 1 - Pacific,NaN,Pacific West,Northwest,NaN,46.377351,-120.308667
2,Suquamish Indian Tribe of the Port Madison Res...,Suquamish,NaN,Tribe,NaN,Leonard,NaN,Forsman,NaN,NaN,...,NaN,Oregon/Washington,Columbia-Pacific Northwest,Region 1 - Pacific,NaN,Pacific West,Northwest,NaN,47.730754,-122.561621
3,Tulalip Tribes of Washington,Tulalip,NaN,Tribe,NaN,Teri,NaN,Gobin,NaN,NaN,...,NaN,Oregon/Washington,Columbia-Pacific Northwest,Region 1 - Pacific,NaN,Pacific West,Northwest,NaN,48.054661,-122.258542
5,Quinault Indian Nation,Quinault,NaN,Tribe,NaN,Guy,NaN,Capoeman,NaN,NaN,...,NaN,Oregon/Washington,Columbia-Pacific Northwest,Region 1 - Pacific,NaN,Pacific West,Northwest,NaN,47.347305,-124.293240
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
582,Cayuga Nation,Cayuga Nation of New York,NaN,Tribe,NaN,Clint,NaN,Halftown,NaN,NaN,...,NaN,Eastern States,NaN,Region 5 - Northeast,NaN,Northeast,Northeast,NaN,42.910622,-76.796622
583,"Cedarville Rancheria, California",Cedarville,NaN,Tribe,NaN,Melissa,NaN,Daniello,NaN,NaN,...,NaN,California,California-Great Basin,Region 8 - Pacific Southwest,NaN,Pacific West,Pacific,NaN,41.483971,-120.545339
584,Cher-Ae Heights Indian Community of the Trinid...,Cher-Ae Heights,Trinidad Rancheria,Tribe,NaN,Garth,NaN,Sundberg,Sr.,NaN,...,NaN,California,California-Great Basin,Region 8 - Pacific Southwest,NaN,Pacific West,Pacific,NaN,41.059291,-124.143125
585,"Cheyenne and Arapaho Tribes, Oklahoma",Cheyenne River,NaN,Tribe,NaN,Reggie,NaN,Wassana,NaN,NaN,...,NaN,New Mexico,Missouri Basin,Region 2 - Southwest,NaN,Intermountain,Southwest,NaN,35.614724,-97.992524
586,Chitimacha Tribe of Louisiana,Chitimacha,NaN,Tribe,NaN,Melissa,M.,Darden,NaN,NaN,...,NaN,Eastern States,NaN,Region 4 - Southeast,NaN,Southeast,Southeast,NaN,29.883239,-91.524796